### ISSUE TITLE
switch button color not  changing

### ISSUE THREAD

**Issue by MadhabaPatra** [codex-iter/AWOL#18]
In **light** mode 
   when  i m **enable notification**  ,the switch button  remains in **same color** .
its color should be **green** when it is on.

**Comment by pawank0411** [comment]
Please attach the Screenshot for the same.
**Mention your device Android Version.**

**Comment by MadhabaPatra** [comment]
Android Version: **android P**
![photo_2019-09-22_00-28-36](https://user-images.githubusercontent.com/42464927/65378007-60643900-dcd0-11e9-8bf0-6a0016fcf36a.jpg)

**Comment by SubhrajitPrusty** [comment]
@Pawan0411 is the issue fixed?
Would you please talk about the issue and what you did?

**Comment by pawank0411** [comment]
@SubhrajitPrusty it wasn't a issue, he asked he's enabling notification in light mode then the color of toggle button is not changing and thought it to be a bug.

**But the color of toggle button will not change in light mode it will of grey color whereas in dark mode it's color is green.**

Thus I closed the issue.

**Comment by SubhrajitPrusty** [comment]
ah, fine then
