### ISSUE TITLE
"Plan a bunk" not working

### ISSUE THREAD

**Issue by salif-04** [codex-iter/AWOL#7]
On clicking on _PLAN A BUNK_ it refreshes the app. The login page opens up, auto verifies the credentials and shows the attendance but the _PLAN A BUNK_ page that was loading earlier is no more opening.

**Comment by mojito9542** [comment]
Will be fixed in the next update

**Comment by SubhrajitPrusty** [comment]
@salif-04 @mojito9542 is it fixed now?

**Comment by salif-04** [comment]
No. After updating the app, on login it is getting crashed. Not even loading the attendance page. 

@SubhrajitPrusty @mojito9542

**Comment by SubhrajitPrusty** [comment]
Which device? ROM and version?

**Comment by salif-04** [comment]
vivo 1601
vivo ROM Funtouch OS_3.0
version - PD1612F_EX_A_3.1.3.1

**Comment by mojito9542** [comment]
fixed
